swagger: '2.0'
info:
  title: "FeatureBucket User API Documentation"
  description: "FeatureBucket user api documentation using swagger."
  version: "1.0.0"
host: "localhost:3000"
schemes:
  - "http"
paths:
  /api/v1/users:
    get:
      produces:
        - application/json
      description: "Get users defined in FeatureBucket"
      responses:
        "200":
          description: "Successfully queried users"
          schema:
            $ref: '#/definitions/user'
    put:
      consumes:
        - application/json
      produces:
        - application/json
      description: "Create a user in FeatureBucket"
      parameters:
        - name: "user"
          in: body
          schema:
            $ref: '#/definitions/user'
          description: "request parameters for creating a user"
          required: true
      responses:
        "200":
          description: "Successfully created user"
          schema:
            $ref: '#/definitions/user'
definitions:
  user:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string
      last_name:
        type: string
      first_name:
        type: string
